### ISSUE TITLE
关闭游戏后立马进行切号，有概率报错

### ISSUE THREAD

**Issue by NOWorEVER** [JamXi233/ZenlessTools#9]
结束代码:-2147467259
完整错误:
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\Program Files\miHoYo Launcher\games\ZenlessZoneZero Game\ZenlessZoneZero.exe' with working directory 'C:\Program Files\miHoYo Launcher\games\ZenlessZoneZero Game'. 拒绝访问。
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ZenlessTools.Depend.GameStartUtil.StartGame()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Core.IUnhandledErrorMethods.Propagate(IObjectReference _obj)
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at ZenlessTools.MainWindow.OnUnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)

**Comment by NOWorEVER** [comment]
大佬试着用alt+F4关闭游戏，这个时候用切换账号功能，就很容易出现，怀疑依旧有进程占用，导致切换账号失败
